<?php

/**
 * Class DatabaseHelper - A lightweight PHP database library that simplifies database operations
 */

class DatabaseHelper
{
    // -----------------------------------------------------------------------------
    // Configuration
    // -----------------------------------------------------------------------------

    private $settings = array(
        // how to handle a connection or initialization error
        // invalid configuration settings are also treated as initialization errors as they could have serious
        //      consequences, ex "cascade_on_delete" is set even though it is not a valid setting in the class
        // if changing the default value, change it in this settings array for connection errors.
        //     the database connection is made in the constructor, so updateSetting() cannot be used to
        //     change this setting until after the connection has been established.
        // valid values: 'exit', 'continue_without_database' 
        // - exit: completely end the program
        // - continue_without_database: the program continues, but subsequent database functions
        //      will not execute. functions that modify data will do nothing and functions
        //      that return data will return empty results
        // note that there is no option to continue_with_database
        'connection_error_action' => 'exit',

        // how to handle a query error - failure while executing a database query
        // valid values: 'exit', 'continue_without_database', 'continue_with_database'
        // - exit: completely end the program
        // - continue_without_database: the program continues, but subsequent database functions
        //      will not execute. functions that modify data will do nothing and functions
        //      that return data will return empty results
        // - continue_with_database: the program continues and subsequent database functions will continue normally
        'query_error_action' => 'continue_without_database',

        // HTML that will be displayed when an error causes the program to exit
        // is only displayed when query_error_action or connection_error_action are set to "exit"
        'error_output_html' => '<div>There was an error loading the page</div>',

        // output debugging details to the screen when an error causes the program to exit
        // is only displayed when query_error_action or connection_error_action are set to "exit"
        // should be set to false in production environments
        'output_error_debugging' => false,

        // on query error, return null
        // affects all(), row(), column(), one(), rowById(), and oneById()
        // default behavior is to return an empty, a blank string, or false depending on the function
        // allows the developer to distinguish between a valid query that returns no results 
        //      ("select * from users where false;") and a query error
        //      ("select * from table_does_not_exist where true")
        'return_null_on_error' => false,

        // the unique identifier column in tables
        // used by all "ById" functions to find a record by identifier
        // will usually not need to be changed since most databases use "id" as the identifier field name
        // for instance, if set to "id", then 
        //      getRowById('users', 12) will process SQL like "select * from users where id=:id;" where
        //      ":uuid" will be bound to 12 using PDO
        'id_field_name' => 'id',

        // maximum number of records to include in each SQL query generated by insertMultiple()
        //      and insertMultipleFieldsValues()
        // these functions automatically split larger sets of rows into multiple queries
        // higher values can be more efficient because fewer queries are needed, but use more 
        //      system resources and increase the chance of exceeding system limitations
        // the default (100) is a very conservative value; values in the tens of thousands
        //     will likely work fine for typical data
        'max_records_per_insert_query' => 100,

        // DELETE and UPDATE queries require a WHERE clause
        // used to avoid accidentally deleting or updating all rows in a table
        // just a simple check that the string "WHERE" is in the query, could still allow a DELETE or UPDATE in certain 
        //      rare cases: "DELETE from places_where_ive_been;" or "UPDATE books SET title='Where the Wild Things Are';"
        // to affect all rows in a table, set WHERE clause to "true", ex: "DELETE FROM places_where_ive_been WHERE true;"
        'delete_and_update_require_where' => true,

        // the maximum number of rows to display as an HTML table when outputting an array using the display() function
        // if an array has more rows, values are displayed using PHP's var_dump function
        'max_rows_for_table_display' => 1000,

        // track processing start and end times (to calculate duration later)
        // useful for testing, but adds some overhead, so normally set to false in production
        //    unless the information is needed for another purpose, such as analysis
        'save_query_run_time' => false
    );


    /**
     * database connection
     *
     * @var PDO
     */
    private $connection = null;

    // should we skip all database operations?
    // will be set on error based on the error type and settings
    private $skipQueries = false;

    // errors - note that errors can come from the database itself for bad queries or from the class receiving invalid parameters
    // last (most recent) error connecting to the database. if set, database queries will be skipped because the database connection failed  
    private $lastConnectionError = '';
    // last (most recent) error from a query. could be due to an invalid parameter passed or an error from the database 
    private $lastQueryError = '';

    // information on the current/previous database operation
    // will be reset when a new query starts processing
    private $insertId = 0;
    // note that Mysql's rowCount() should be consistent for UPDATE, DELETE, and INSERT queries,
    //      but for other queries the returned value may depend on the PHP version, database driver, and settings
    private $rowCount = 0;
    private $queryError = '';
    private $isSuccess = false;
    private $sql = '';
    private $binds = array();
    private $returnType = '';
    private $keyField = '';
    private $valueField = '';
    private $startTime = 0;
    private $endTime = 0;

    private $hasDbConnection = false;

    /**
     * constructor
     * connects to the database. sets the connection variable
     * may set hasDbConnection or lastConnectionError if needed
     * 
     * @param string $dbName
     * @param string $host
     * @param string $user
     * @param string $pass
     */
    public function __construct($dbName, $host, $user, $pass)
    {
        $dbName = $this->checkIdentifier($dbName, '__construct() dbname');
        if (empty($dbName)) {
            $this->exitProgramError('invalid dbname in class constructor', true);
            return false;
        }

        $opt = array(
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_SILENT,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        );

        try {
            $this->connection = new PDO(
                'mysql:host=' . $host . ';dbname=' . $dbName . ';charset=utf8mb4',
                $user,
                $pass,
                $opt
            );
        } catch (PDOException $e) {
            $this->connection = null;
            $this->exitProgramError($e->getMessage(), true);
            return;
        }

        $this->hasDbConnection = true;
        $this->skipQueries = false;
    }


    // -----------------------------------------------------------------------------
    // Settings
    // -----------------------------------------------------------------------------

    /**
     * set a configuration setting
     * the setting name must exist in the $settings array
     * the value must be valid for the specified setting
     * example: $db->updateSetting('save_query_run_time', true);
     * supports chaining: $db->updateSetting('save_query_run_time', true)->updateSetting('connection_error_action', 'exit');
     * 
     * @param string $setting
     * @param mixed $value
     * @return DatabaseHelper
     */
    public function updateSetting($setting, $value)
    {
        if (!isset($this->settings[$setting])) {
            $this->exitProgramError("DatabaseHelper updateSetting() received invalid setting: " . $setting, true);
            return $this;
        }

        // valid settings 
        //      boolean = save_query_run_time, output_error_debugging, return_null_on_error, delete_and_update_require_where
        //      integer = max_records_per_insert_query, max_rows_for_table_display
        //      string = connection_error_action, query_error_action, error_output_html, id_field_name

        if (
            $setting === 'save_query_run_time' ||
            $setting === 'output_error_debugging' ||
            $setting === 'return_null_on_error' ||
            $setting === 'delete_and_update_require_where'
        ) {
            if (empty($value) || $value === 'false') {
                $value = false;
            } else {
                $value = true;
            }
        } elseif ($setting === 'max_records_per_insert_query' || $setting === 'max_rows_for_table_display') {
            if (!is_numeric($value)) {
                $this->exitProgramError("DatabaseHelper updateSetting() value must be a number: " . $setting, true);
                return $this;
            }
            $value = intval($value);

            // upper limit set to 10k
            if ($setting === 'max_records_per_insert_query' && ($value < 1 || $value > 10000)) {
                $this->exitProgramError('value is invalid for setting: max_records_per_insert_query. value must be between 1 and 10,000', true);
                return $this;
            }

            // upper limit set to 10k
            // lower limit set to 2. showing 1 row defeats the purpose and users could set 1 thinking that they're setting a boolean value
            if ($setting === 'max_rows_for_table_display' && ($value < 2 || $value > 10000)) {
                $this->exitProgramError('value is invalid for setting: max_rows_for_table_display. value must be between 2 and 10,000', true);
                return $this;
            }
        } elseif ($setting === 'connection_error_action') {
            // only valid values
            if ($value !== 'exit' && $value !== 'continue_without_database') {
                $this->exitProgramError('value is invalid for setting: connection_error_action. value must be "exit" or "continue_without_database"', true);
                return $this;
            }
        } elseif ($setting === 'query_error_action') {
            // only valid values
            if ($value !== 'exit' && $value !== 'continue_without_database' && $value !== 'continue_with_database') {
                $this->exitProgramError('value is invalid for setting: query_error_action. value must be "exit", "continue_without_database", or "continue_with_database"', true);
                return $this;
            }
        } elseif ($setting === 'error_output_html') {
            if (!is_string($value)) {
                $this->exitProgramError('value is invalid for setting: error_output_html. value must be "string" (' . gettype($value) . ' passed)', true);
                return $this;
            }
        } elseif ($setting === 'id_field_name') {
            if (!is_string($value)) {
                $this->exitProgramError('value is invalid for setting: id_field_name. value must be "string" (' . gettype($value) . ' passed)', true);
                return $this;
            }
            $value = $this->checkIdentifier($value, 'id_field_name setting');
            if (empty($value)) {
                $this->exitProgramError('invalid id_field_name setting', true);
                return $this;
            }
        } else {
            // should not get here. this is just a failsafe in case a valid settings is not checked
            $this->exitProgramError("DatabaseHelper updateSetting() setting not available: " . $setting, true);
            return $this;
        }

        $this->settings[$setting] = $value;

        return $this;
    }


    // -----------------------------------------------------------------------------
    // Get Last Error and Connection Info
    // -----------------------------------------------------------------------------

    /**
     * return the last (most recent) error
     * note that this is NOT the error from the last query
     * will include connection errors (connection and initialization) and query errors (pre check and query itself)
     * example: $error = $db->lastError();
     * 
     * @return string
     */
    public function lastError()
    {
        // note that there will not be both error types since connection errors will stop queries from running
        if (!empty($this->lastConnectionError)) {
            return $this->lastConnectionError;
        }
        if (!empty($this->lastQueryError)) {
            return $this->lastQueryError;
        }
        return '';
    }

    /**
     * return if a database connection has been made or not
     * example: $hasDbConnection = $db->hasDbConnection();
     * 
     * @return boolean
     */
    public function hasDbConnection()
    {
        return $this->hasDbConnection;
    }


    // -----------------------------------------------------------------------------
    // Get Last Query Info
    // -----------------------------------------------------------------------------

    /**
     * get the identifier of the last query
     * will be 0 unless the last query was a successful insert
     * example: $id = $db->insertId();
     * 
     * @return integer
     */
    public function insertId()
    {
        return $this->insertId;
    }

    /**
     * get the number of rows affected by the last query
     * example: $rowCount = $db->rowCount();
     * 
     * @return integer
     */
    public function rowCount()
    {
        return $this->rowCount;
    }

    /**
     * get the error from the last query
     * note that this differs from the last error
     * example: $errorText = $db->error();
     * 
     * @return string
     */
    public function error()
    {
        return $this->queryError;
    }

    /**
     * return if the last query was successful
     * will be boolean (true or false)
     * example: $isSuccess = $db->success();
     * 
     * @return boolean
     */
    public function success()
    {
        if ($this->isSuccess) {
            return true;
        }
        return false;
    }

    /**
     * return the duration of the last query in seconds
     * example: $durationInSeconds = $db->duration();
     * 
     * @return integer
     */
    public function duration()
    {
        if ($this->startTime && $this->endTime) {
            $duration = $this->endTime - $this->startTime;
            return number_format($duration, 6);
        }
        return 0;
    }

    /**
     * return the last SQL query
     * example: $sql = $db->sql();
     * 
     * @return string
     */
    public function sql()
    {
        return $this->sql;
    }

    /**
     * return the PDO binds for the last query
     * example: $binds = $db->binds();
     * 
     * @return array
     */
    public function binds()
    {
        return $this->binds;
    }    


    // -----------------------------------------------------------------------------
    // Development / Debugging
    // -----------------------------------------------------------------------------

    /**
     * display information about the last query
     * data includes: raw SQL, binds, duration, errors, etc
     * example: $db->displayLastQueryInfo();
     */
    public function displayLastQueryInfo()
    {
        $ar = array(
            'type' => $this->returnType,
            'sql' => $this->sql,
            'binds' => $this->binds,
            'keyField' => $this->keyField,
            'valueField' => $this->valueField,
            'rowCount' => $this->rowCount,
            'insertId' => $this->insertId,
            'isSuccess' => $this->isSuccess,
            'queryError' => $this->queryError
        );
        if ($this->settings['save_query_run_time']) {
            $duration = 0;
            if ($this->startTime && $this->endTime) {
                $duration = $this->endTime - $this->startTime;
            }
            $ar['duration'] = number_format($duration, 6) . ' seconds';
        }

        $this->display($ar);
    }

    /**
     * shortcut for displayLastQuery
     * example: $db->info();
     */
    public function info()
    {
        $this->displayLastQueryInfo();
    }

    /**
     * display a value for debugging
     * displays arrays as an HTML table to make query results easier to read
     * displays other values using PHP's var_dump() function
     * note that this function is not intended for displaying data in a website or web interface;
     *     it is intended to be a quick way to view database results and other information while developing
     * example: $db->display($customers);
     * 
     * @param mixed $value
     */
    public function display($value)
    {
        $this->displayInternal($value);
    }

    /**
     * output a list of all tables in the database
     * example: $db->tables();
     */
    public function tables()
    {
        $this->resetInfo();
        $this->returnType = 'col';

        $this->sql = 'SHOW TABLES;';

        $tables = $this->makeQuery();
        $this->display($tables);
    }

    /**
     * output a list of all fields in a table
     * example: $db->fields('customers');
     * 
     * @param string $table
     */
    public function fields($table)
    {
        $this->resetInfo();
        $this->returnType = 'all';

        $table = $this->checkIdentifier($table, 'fields table');
        if (empty($table)) {
            return $this->getReturnInvalid();
        }

        $this->sql = 'DESCRIBE `' . $table . '`;';
        $fields = $this->makeQuery();

        $this->display($fields);
    }


    // -----------------------------------------------------------------------------
    // Retrieve Data From Raw SQL
    // -----------------------------------------------------------------------------

    /**
     * execute SQL and return all result rows
     * returns a 2-dimensional array, with each row as an associative key/value array
     * optionally use $keyField to use a field as the array key. * note that array keys are required and unique, so null or duplicate values may result in rows being overwritten or omitted.
     * example: $customers = $db->all('select * from customers where last_name = :last_name;', array(':last_name' => 'Jones'), 'id');
     * 
     * @param string $sql
     * @param array $binds
     * @param string $keyField
     * @return array
     */
    public function all($sql, $binds = array(), $keyField = '')
    {
        $this->resetInfo();
        $this->returnType = 'all';
        $this->sql = $sql;

        $this->binds = $binds;
        $this->keyField = $keyField;

        return $this->makeQuery();
    }

    /**
     * execute SQL and return the first row
     * returns a 1-dimensional associative array containing the row's fields and values
     * example: $customer = $db->row('select * from customers where last_name = :last_name order by first_name limit 1;', array(':last_name' => 'Jones'));
     * 
     * @param string $sql
     * @param array $binds
     * @return array
     */
    public function row($sql, $binds = array())
    {
        $this->resetInfo();
        $this->returnType = 'row';
        $this->sql = $sql;

        $this->binds = $binds;

        return $this->makeQuery();
    }

    /**
     * execute SQL and return all values from a single column
     * optionally use $keyField to use a field as the array key. * note that array keys are required and unique, 
     *      so null or duplicate values may result in rows being overwritten or omitted from the returned array.
     * optionally use $valueField to specify which field's values to return
     * if $valueField is not set, the first selected field is used for the values
     * for a non-associative array, leave $keyField and $valueField empty and select only one field
     * associative example: $customerNames = $db->column('select id, first_name from customers where last_name = :last_name order by first_name;', array(':last_name' => 'Jones'), 'id', 'first_name');
     * non-associative example: $customerNames = $db->column('select first_name from customers where last_name = :last_name order by first_name;', array(':last_name' => 'Jones'));
     * 
     * @param string $sql
     * @param array $binds
     * @param string $keyField
     * @param string $valueField
     * @return array
     */
    public function column($sql, $binds = array(), $keyField = '', $valueField = '')
    {
        $this->resetInfo();
        $this->returnType = 'col';
        $this->sql = $sql;
        $this->binds = $binds;
        $this->keyField = $keyField;
        $this->valueField = $valueField;

        return $this->makeQuery();
    }

    /**
     * shortcut for the column function
     * associative example: $customerNames = $db->col('select id, first_name from customers where last_name = :last_name order by first_name;', array(':last_name' => 'Jones'), 'id', 'first_name');
     * non-associative example: $customerNames = $db->col('select first_name from customers where last_name = :last_name order by first_name;', array(':last_name' => 'Jones'));
     * 
     * @param string $sql
     * @param array $binds
     * @param string $keyField
     * @param string $valueField
     * @return array
     */
    public function col($sql, $binds = array(), $keyField = '', $valueField = '')
    {
        return $this->column($sql, $binds, $keyField, $valueField);
    }

    /**
     * execute SQL and return a single value from the first result row
     * optionally use $valueField to specify which field's value to return
     * if $valueField is not set, the first field's value is returned
     * it is generally better to leave $valueField empty and select only one field
     * it is better to add LIMIT 1 to the SQL query to avoid retrieving unnecessary rows
     * example usage: $firstName = $db->one('select first_name from customers where last_name = :last_name order by first_name limit 1;', array(':last_name' => 'Jones'));
     * 
     * @param string $sql
     * @param array $binds
     * @param string $valueField
     * @return string|int|float
     */
    public function one($sql, $binds = array(), $valueField = '')
    {
        $this->resetInfo();
        $this->returnType = 'one';
        $this->sql = $sql;
        $this->binds = $binds;
        $this->valueField = $valueField;

        return $this->makeQuery();
    }


    // -----------------------------------------------------------------------------
    // Modify Database (Insert, Update, Delete, Alter, etc) From Raw SQL
    // -----------------------------------------------------------------------------

    /**
     * execute SQL when no result values are needed
     * generally only needed for delete or update
     * returns true if the query succeeds and false if it fails; 
     *      success means the query executed without errors, not that any data was returned or changed
     * example: $db->query('delete from customers where last_name = :last_name;', array(':last_name' => 'Jones'));
     * 
     * @param string $sql
     * @param array $binds
     * @return boolean
     */
    public function query($sql, $binds = array())
    {
        $this->resetInfo();
        $this->returnType = 'query';
        $this->sql = $sql;
        $this->binds = $binds;

        return $this->makeQuery();
    }


    // -----------------------------------------------------------------------------
    // Retrieve Data From Parameters (converted to SQL)
    // -----------------------------------------------------------------------------

    /**
     * return the number of rows in a table
     * example: $totalCustomers = $db->count('customers');
     *
     * @param string $table
     * @return int
     */
    public function count($table)
    {
        $this->resetInfo();
        $this->returnType = 'one';

        $returnInvalid = $this->getReturnInvalid();

        $table = $this->checkIdentifier($table, 'count() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        $this->sql = 'SELECT COUNT(*) AS `tot` FROM `' . $table . '`;';

        return $this->makeQuery();
    }

    /**
     * get a row from a table using its identifier field (usually "id")
     * returns a 1-dimensional associative array containing the row's fields and values
     * uses the id_field_name setting to determine the identifier field
     * runs query "select * from [table] where id=[id]"
     * example: $customer = $db->rowById('customers', 25);
     * 
     * @param string $table
     * @param int $id
     * @return array
     */
    public function rowById($table, $id)
    {
        $this->resetInfo();
        $this->returnType = 'row';

        $table = $this->checkIdentifier($table, 'rowById() table');
        $idFieldName = $this->checkIdentifier($this->settings['id_field_name'], 'rowById() id_field_name setting');
        if (empty($table) || empty($idFieldName)) {
            return $this->getReturnInvalid();
        }

        $this->sql = 'SELECT * FROM `' . $table . '` WHERE `' . $idFieldName . '` = :id limit 1;';
        $this->binds = array(':id' => $id);

        return $this->makeQuery();
    }

    /**
     * get a single value from a table using its identifier field (usually "id")
     * returns a single value from the specified field
     * uses the id_field_name setting to determine the identifier field
     * runs query "select [field] from [table] where id=[id]"
     * example usage: $firstName = $db->oneById('customers', 25, 'first_name');
     * 
     * @param string $table
     * @param int $id
     * @param string $field
     * @return string|int|float
     */
    public function oneById($table, $id, $field)
    {
        $this->resetInfo();
        $this->returnType = 'one';

        $table = $this->checkIdentifier($table, 'oneById() table');
        $idFieldName = $this->checkIdentifier($this->settings['id_field_name'], 'oneById() id_field_name setting');
        $field = $this->checkIdentifier($field, 'oneById() field');
        if (empty($table) || empty($idFieldName) || empty($field)) {
            return $this->getReturnInvalid();
        }

        $this->sql = 'SELECT `' . $field . '` FROM `' . $table . '` WHERE `' . $idFieldName . '` = :id LIMIT 1;';
        $this->binds = array(':id' => $id);

        return $this->makeQuery();
    }


    // -----------------------------------------------------------------------------
    // Modify Database (Insert, Update, Delete, Alter, etc) From Parameters (converted to SQL)
    // -----------------------------------------------------------------------------    

    /**
     * insert a new row into a table
     * returns the identifier (id) of the newly inserted row
     * uses the array keys as field names and the array values as values
     * example: $newCustomerId = $db->insert('customers', array('first_name' => 'John', 'last_name' => 'Jones'));
     * 
     * @param string $table
     * @param array $values
     * @return int
     */
    public function insert($table, $values)
    {
        $this->resetInfo();
        $this->returnType = 'insert';

        $returnInvalid = $this->getReturnInvalid();
        $table = $this->checkIdentifier($table, 'insert() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($values)) {
            $this->exitProgramError('insert() - $values is not an array (' . gettype($values) . ' passed)');
            return $returnInvalid;
        }
        if (count($values) < 1) {
            $this->exitProgramError('insert() - $values array is empty (0 values)');
            return $returnInvalid;
        }

        $fieldStr = $valueStr = '';
        $binds = array();
        $sep = '';
        foreach ($values as $field => $value) {
            $field = $this->checkIdentifier($field, 'insert() field (array key)');
            if (empty($field)) {
                return $returnInvalid;
            }
            $fieldStr .= $sep . '`' . $field . '`';
            $rawSql = $this->getRawString($value);
            if ($rawSql) {
                $valueStr .= $sep . ' ' . $rawSql . ' ';
            } else {
                $valueStr .= $sep . ':' . $field;
                $binds[':' . $field] = $value;
            }
            $sep = ', ';
        }
        $this->sql = 'INSERT INTO `' . $table . '` (' . $fieldStr . ') VALUES (' . $valueStr . ');';
        $this->binds = $binds;

        return $this->makeQuery();
    }

    /**
     * insert a new row into a table
     * returns true if all rows are inserted successfully and false if any query fails
     * uses the array keys as field names and the array values as field values
     * all rows must contain the same field names
     * splits the insert into multiple queries when the number of rows exceeds the max_records_per_insert_query setting
     * pre-validates all rows before inserting, so a misformatted row prevents any rows from being inserted
     * example: 
     * $isSuccess = $db->insertMultiple('customers', array(
     *     array('first_name' => 'John', 'last_name' => 'Jones'),
     *     array('first_name' => 'Susan', 'last_name' => 'Smith')
     *  ));
     * 
     * @param string $table
     * @param array $rows
     * @return boolean
     */
    public function insertMultiple($table, $rows)
    {
        $this->resetInfo();
        $this->returnType = 'insertMultiple';

        $returnInvalid = $this->getReturnInvalid();

        $table = $this->checkIdentifier($table, 'insertMultiple() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($rows)) {
            $this->exitProgramError('insertMultiple() - $rows is not an array (' . gettype($rows) . ' passed)');
            return $returnInvalid;
        }
        if (count($rows) < 1) {
            $this->exitProgramError('InsertMultiple() - $rows array is empty (0 rows)');
            return $returnInvalid;
        }

        // default value, will change after inserts
        $returnValue = $returnInvalid;

        // pre-check all rows
        $matchRow = array();
        $rowKeys = array();
        $matchRowCount = 0;
        foreach ($rows as $row) {
            if (!is_array($row)) {
                $this->exitProgramError('InsertMultiple() - $rows is not a 2 dimensional array');
                return $returnInvalid;
            }

            if (empty($matchRow)) {
                // our first row that we will use to compare to others has not been set yet
                // do some validation and set it

                if (count($row) < 1) {
                    $this->exitProgramError('InsertMultiple() - the first row in $rows is empty (0 fields)');
                    return $returnInvalid;
                }
                foreach ($row as $field => $value) {
                    $fieldClean = $this->checkIdentifier($field, 'insertMultiple() row field (array key)', true);
                    if (empty($fieldClean)) {
                        $this->exitProgramError('InsertMultiple() - $row has a row with an invalid field name (array key)');
                        return $returnInvalid;
                    }
                }

                // $matchRow will be compared with every other row, in these checks keys must be the same
                $matchRow = $row;
                $matchRowCount = count($matchRow);
                $rowKeys = array_keys($matchRow);
            } else {
                if ($matchRowCount !== count($row)  || array_diff_key($row, $matchRow)) {
                    $this->exitProgramError('InsertMultiple() - mismatched field name (array key) in $rows');
                    return $returnInvalid;
                }
            }
        }

        $fieldStr = '';
        foreach ($rowKeys as $key) {
            if (!empty($fieldStr)) {
                $fieldStr .= ',';
            }
            $fieldStr .= '`' . $key . '`';
        }

        $maxInsertRows = intval($this->settings['max_records_per_insert_query']);

        $valStr = '';
        $binds = array();
        $ctr = 0;
        $isFirstRow = true;
        foreach ($rows as $row) {
            $ctr++;
            if ($isFirstRow) {
                $isFirstRow = false;
            } else {
                $valStr .= ',';
            }

            $isFirstField = true;
            $valStr .= '(';
            $fieldCtr = 0;
            foreach ($rowKeys as $field) {
                $fieldCtr++;
                if ($isFirstField) {
                    $isFirstField = false;
                } else {
                    $valStr .= ',';
                }
                $rawSql = $this->getRawString($row[$field]);
                if ($rawSql) {
                    $valStr .= ' ' . $rawSql . ' ';
                } else {
                    $bindKey = ':v' . $ctr . '_' . $fieldCtr;
                    $valStr .= $bindKey;
                    $binds[$bindKey] = $row[$field];
                }
            }
            $valStr .= ')';

            if ($ctr >= $maxInsertRows) {
                $this->sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
                $this->binds = $binds;
                $returnValue = $this->makeQuery();
                if (!$returnValue) {
                    return $returnInvalid;
                }
                // reset to start building next insert
                $isFirstRow = true;
                $valStr = '';
                $binds = array();
                $ctr = 0;
            }
        }

        if (!empty($valStr)) {
            // insert remaining unprocessed records
            $this->sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
            $this->binds = $binds;
            $returnValue = $this->makeQuery();
            if (!$returnValue) {
                return $returnInvalid;
            }
        }

        return $returnValue;
    }

    /**
     * insert multiple new rows into a table using a separate array of field names
     * returns true if all rows are inserted successfully and false if any query fails
     * uses $fields for the field names and $dataRows for the row values
     * all rows must contain the same number of values as the number of fields
     * pre-validates all rows before inserting, so a misformatted row prevents any rows from being inserted
     * splits the insert into multiple queries when the number of rows exceeds the max_records_per_insert_query setting
     * example: 
     * $isSuccess = $db->insertMultipleFieldsValues(
     *      'customers', 
     *      array('first_name', 'last_name'), 
     *      array(
     *          array('John', 'Jones'),
     *          array('Jane', 'Smith')
     *      )
     * );
     * 
     * @param string $table
     * @param array $fields
     * @param array $dataRows
     * @return boolean
     */
    public function insertMultipleFieldsValues($table, $fields, $dataRows)
    {
        $this->resetInfo();
        $this->returnType = 'insertMultiple';

        $returnInvalid = $this->getReturnInvalid();

        $table = $this->checkIdentifier($table, 'insertMultipleFieldsValues() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($fields)) {
            $this->exitProgramError('insertMultipleFieldsValues() - $fields is not an array (' . gettype($fields) . ' passed)');
            return $returnInvalid;
        }

        $fieldCount = count($fields);
        if ($fieldCount < 1) {
            $this->exitProgramError('insertMultipleFieldsValues() - $fields array is empty (0 fields)');
            return $returnInvalid;
        }
        if (count(array_unique($fields)) !== $fieldCount) {
            $this->exitProgramError('insertMultipleFieldsValues() - $fields values must be unique');
            return $returnInvalid;
        }

        if (!is_array($dataRows)) {
            $this->exitProgramError('insertMultipleFieldsValues() - $dataRows is not an array (' . gettype($dataRows) . ' passed)');
            return $returnInvalid;
        }
        if (count($dataRows) < 1) {
            $this->exitProgramError('insertMultipleFieldsValues() - $dataRows array is empty (0 rows)');
            return $returnInvalid;
        }

        // default value, will change after inserts
        $returnValue = $returnInvalid;

        // pre-check all rows

        foreach ($dataRows as $row) {
            if (!is_array($row)) {
                $this->exitProgramError('insertMultipleFieldsValues() - $dataRows is not a 2 dimensional array');
                return $returnInvalid;
            }

            if ($fieldCount !== count($row)) {
                $this->exitProgramError('insertMultipleFieldsValues() - mismatched field count in $dataRows rows');
                return $returnInvalid;
            }
        }

        $fieldStr = '';
        foreach ($fields as $field) {
            $field = $this->checkIdentifier($field, 'insertMultipleFieldsValues() field');
            if (empty($field)) {
                return $returnInvalid;
            }

            if (!empty($fieldStr)) {
                $fieldStr .= ',';
            }
            $fieldStr .= '`' . $field . '`';
        }

        $maxInsertRows = intval($this->settings['max_records_per_insert_query']);

        $valStr = '';
        $binds = array();
        $ctr = 0;
        $isFirstRow = true;
        foreach ($dataRows as $row) {
            $ctr++;
            if ($isFirstRow) {
                $isFirstRow = false;
            } else {
                $valStr .= ',';
            }

            $isFirstField = true;
            $valStr .= '(';
            $valCtr = 0;
            foreach ($row as $value) {
                if ($isFirstField) {
                    $isFirstField = false;
                } else {
                    $valStr .= ',';
                }
                $valCtr++;

                $rawSql = $this->getRawString($value);
                if ($rawSql) {
                    $valStr .= ' ' . $rawSql . ' ';
                } else {
                    $bindKey = ':v' . $ctr . '_' . $valCtr;
                    $valStr .= $bindKey;
                    $binds[$bindKey] = $value;
                }
            }
            $valStr .= ')';

            if ($ctr >= $maxInsertRows) {
                $this->sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
                $this->binds = $binds;
                $returnValue = $this->makeQuery();
                if (!$returnValue) {
                    return $returnInvalid;
                }

                // reset to start building next insert
                $isFirstRow = true;
                $valStr = '';
                $binds = array();
                $ctr = 0;
            }
        }

        if (!empty($valStr)) {
            $this->sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
            $this->binds = $binds;
            $returnValue = $this->makeQuery();
            if (!$returnValue) {
                return $returnInvalid;
            }
        }

        return $returnValue;
    }

    /**
     * update rows in a table
     * returns true if the query succeeds and false if it fails
     * uses $values to specify the fields and values to update
     * uses $whereSql to specify which rows to update
     * $whereSql is required to avoid mistakes; if all rows need to be updated, set $whereSql to "true" to match all rows.
     * optionally use $whereBinds to bind values to the $whereSql statement
     * example: $isSuccess = $db->update('customers', array('first_name' => 'John'), 'last_name = :last_name', array(':last_name' => 'Jones'));
     * 
     * @param string $table
     * @param array $values
     * @param string $whereSql
     * @param array $whereBinds
     * @return boolean
     */
    public function update($table, $values, $whereSql, $whereBinds = array())
    {
        $this->resetInfo();
        $this->returnType = 'query';

        $returnInvalid = $this->getReturnInvalid();

        $table = $this->checkIdentifier($table, 'update() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($values)) {
            $this->exitProgramError('update() - $values is not an array (' . gettype($values) . ' passed)');
            return $returnInvalid;
        }
        if (count($values) < 1) {
            $this->exitProgramError('update() - $values array is empty (0 values)');
            return $returnInvalid;
        }

        if (!is_string($whereSql)) {
            $this->exitProgramError('update() - $whereSql is not a string (' . gettype($whereSql) . ' passed)');
            return $returnInvalid;
        }
        if (empty($whereSql)) {
            $this->exitProgramError('update() - $whereSql is empty');
            return $returnInvalid;
        }


        $setStr = '';
        //$ctr = 0;
        $binds = $whereBinds;
        //$currentUnixTime = time();
        $ctr = 0;
        foreach ($values as $field => $value) {
            $ctr++;
            $field = $this->checkIdentifier($field, 'update() field');
            if (empty($field)) {
                return $returnInvalid;
            }

            if (!empty($setStr)) {
                $setStr .= ',';
            }
            //$ctr++;
            $bindKey = ':v' . $ctr;
            //$ctr = 1;
            while (isset($binds[$bindKey]) || isset($binds[ltrim($bindKey, ':')])) {
                // there was a collision in the naming, move on to the next counter.
                $ctr++;
                $bindKey = ':v' . $ctr;
            }
            $rawSql = $this->getRawString($value);
            if ($rawSql) {
                $setStr .= '`' . $field . '`=' . $rawSql . ' ';
            } else {
                $setStr .= '`' . $field . '`=' . $bindKey;
                $binds[$bindKey] = $value;
            }
        }

        $this->sql = 'UPDATE `' . $table . '` SET ' . $setStr . ' WHERE ' . $whereSql . ';';
        $this->binds = $binds;
        return $this->makeQuery();
    }

    /**
     * update a row in a table using its identifier field (usually "id")
     * returns true if the query succeeds and false if it fails
     * uses the id_field_name setting to determine the identifier field
     * example: $isSuccess = $db->updateById('customers', array('first_name' => 'John'), 25);
     * 
     * @param string $table
     * @param array $values
     * @param int $id
     * @return boolean
     */
    public function updateById($table, $values, $id)
    {
        // reset needed even though the update function will reset again.
        // but if errors are generated in this function, we don't want previous query info in debugging output
        $this->resetInfo();
        $this->returnType = 'query';

        $returnInvalid = $this->getReturnInvalid();

        $table = $this->checkIdentifier($table, 'updateById() table');
        if (empty($table)) {
            return $returnInvalid;
        }
        $idFieldName = $this->checkIdentifier($this->settings['id_field_name'], 'updateById() id_field_name setting');
        if (empty($idFieldName)) {
            return $returnInvalid;
        }

        $whereSql = '`' . $idFieldName . '`=:id';
        $binds = array(':id' => $id);
        return $this->update($table, $values, $whereSql, $binds);
    }

    /**
     * delete a row from a table using its identifier field (usually "id")
     * returns true if the query succeeds and false if it fails
     * uses the id_field_name setting to determine the identifier field
     * runs query "delete from [table] where id=[id]"
     * example: $isSuccess = $db->deleteById('customers', 25);
     * 
     * @param string $table
     * @param int $id
     * @return boolean
     */
    public function deleteById($table, $id)
    {
        $this->resetInfo();
        $this->returnType = 'query';

        $returnInvalid = $this->getReturnInvalid();

        $table = $this->checkIdentifier($table, 'deleteById() table');
        $idFieldName = $this->checkIdentifier($this->settings['id_field_name'], 'deleteById() id_field_name setting');
        if (empty($table) || empty($idFieldName)) {
            return $returnInvalid;
        }

        $this->sql = 'DELETE FROM `' . $table . '` WHERE `' . $idFieldName . '`=:id;';
        $this->binds = array(':id' => $id);

        return $this->makeQuery();
    }


    // -----------------------------------------------------------------------------
    // SQL Expression Helpers
    // -----------------------------------------------------------------------------    

    /**
     * mark a value as raw SQL instead of a value to be bound
     * raw SQL is inserted directly into the query and is not protected by PDO binding
     * only use with SQL that is known to be safe
     * example: $db->raw('CURDATE()')
     * full example: full example: $db->insert('users', array('username'=>'bob_jones', 'signup_date'=>$db->raw('CURDATE()')));
     *
     * @param string $value
     * @return array
     */
    public function raw($value)
    {
        return array('raw_sql' => $value);
    }

    
    // -----------------------------------------------------------------------------
    // Internal Processing Functions (Queries)
    // -----------------------------------------------------------------------------

    /**
     * prepare and execute SQL
     * used internally by public methods to process queries
     * 
     * @return mixed
     */
    private function makeQuery()
    {
        $returnInvalid = $this->getReturnInvalid();

        if ($this->skipQueries) {
            if (empty($this->queryError)) {
                $this->queryError = 'Query skipped due to previous error';
            }
            return  $returnInvalid;
        }

        $sql = $this->sql;
        if (!is_string($sql)) {
            $this->exitProgramError('makeQuery() - $sql is not a string');
            return $returnInvalid;
        }

        // trim the class and function variables
        $this->sql = $sql = trim($sql);
        if (empty($sql)) {
            $this->exitProgramError('makeQuery() - $sql is empty');
            return $returnInvalid;
        }

        $binds = $this->binds;
        // convert any falsy value to an empty array. this allows any falsey (null, false, '') to be passed when there are no binds
        if (empty($binds)) {
            $binds = array();
        }
        if (!is_array($binds)) {
            $this->exitProgramError('makeQuery() - $binds must be an array');
            return $returnInvalid;
        }

        // to avoid mistakes, if delete_and_update_require_where is set, UPDATE and DELETE queries require WHERE
        // note that this is a simple test that sql has the string "WHERE". so "delete from places_where_ive_been;" will incorrectly 
        //    be seen as having a WHERE clause
        if (!empty($this->settings['delete_and_update_require_where'])) {
            // check if it's an UPDATE or DELETE query 
            $sqlFirst6Lc = strtolower(substr($sql, 0, 6));
            if ($sqlFirst6Lc === 'update' || $sqlFirst6Lc === 'delete') {
                // check if the string "WHERE" is in the SQL
                if (stripos($sql, 'where') === false) {
                    $this->exitProgramError(strtoupper($sqlFirst6Lc) . ' query requires a WHERE clause');
                    return $returnInvalid;
                }
            }
        }

        $statement = $this->connection->prepare($sql);
        if (!$statement) {
            //$this->setInfo(false, $statement);
            $this->queryErrorSave($statement);
            return $returnInvalid;
        }

        foreach ($binds as $field => $value) {
            $field = $this->checkIdentifier($field, 'bind field', true);
            if (empty($field)) {
                return $returnInvalid;
            }
            $success =  $statement->bindValue($field, $value);
            if (!$success) {
                $this->queryErrorSave($statement);
                return $returnInvalid;
            }
        }
        $success = $statement->execute();

        if ($this->settings['save_query_run_time']) {
            $this->endTime = microtime(true);
        }

        if (!$success) {
            $this->queryErrorSave($statement);
            return $returnInvalid;
        }

        $this->querySuccessSave($statement);

        return $this->getReturnValue($statement);
    }

    /**
     * process query results and return the appropriate value
     * used internally by makeQuery() to process returned data
     * returns the appropriate invalid value when the query cannot be processed or fails
     * 
     * @param PDOStatement $statement
     * @return string|false
     */
    private function getReturnValue($statement)
    {
        $returnInvalid = $this->getReturnInvalid();

        $type = $this->returnType;

        if (!$statement) {
            return $returnInvalid;
        }

        $keyField = $this->keyField;
        $valueField = $this->valueField;

        if ($type == 'all') {
            $fetchAll = $statement->fetchAll(PDO::FETCH_ASSOC);
            if (empty($keyField)) {
                return $fetchAll;
            }

            $ar = array();
            foreach ($fetchAll as $row) {
                if (!array_key_exists($keyField, $row)) {
                    $this->exitProgramError("key field ($keyField) is not found. available fields: " . implode(', ', array_keys($row)));
                    return $returnInvalid;
                }
                $ar[$row[$keyField]] = $row;
            }
            return $ar;
        }

        if ($type == 'row') {
            $row = $statement->fetch(PDO::FETCH_ASSOC);

            if (!$row) {
                return array();
            }
            return $row;
        }

        if ($type == 'col') {
            $ar = array();
            if (empty($keyField) && empty($valueField)) {
                $val = $statement->fetchColumn();
                while ($val !== false) {
                    $ar[] = $val;
                    $val = $statement->fetchColumn();
                }
                return $ar;
            }

            $fetchAll = $statement->fetchAll(PDO::FETCH_ASSOC);
            foreach ($fetchAll as $row) {
                $k = $v = null;

                if (!empty($valueField)) {
                    if (!array_key_exists($valueField, $row)) {
                        $this->exitProgramError("value field ($valueField) is not found. available fields: " . implode(', ', array_keys($row)));
                        return $returnInvalid;
                    }
                    $v = $row[$valueField];
                } else {
                    $v = reset($row);
                }

                if (!empty($keyField)) {
                    if (!array_key_exists($keyField, $row)) {
                        $this->exitProgramError("key field ($keyField) is not found. available fields: " . implode(', ', array_keys($row)));
                        return $returnInvalid;
                    }
                    $k = $row[$keyField];
                }

                if (!is_null($k)) {
                    $ar[$k] = $v;
                } else {
                    $ar[] = $v;
                }
            }
            return $ar;
        }

        if ($type == 'one') {
            if (empty($valueField)) {
                $row = $statement->fetch(PDO::FETCH_NUM);
                if ($row) {
                    return $row[0];
                }
            } else {
                $row = $statement->fetch(PDO::FETCH_ASSOC);
                if ($row) {
                    if (!array_key_exists($valueField, $row)) {
                        $this->exitProgramError("value field ($valueField) is not found. available fields: " . implode(', ', array_keys($row)));
                        return $returnInvalid;
                    }
                    return $row[$valueField];
                }
            }
            return '';
        }

        if ($type == 'insert') {
            return $this->insertId;
        }

        return true;
    }

    /**
     * determine the value to return when a query fails or returns no results
     * used internally by makeQuery() and getReturnValue()
     * returns null for errors when the return_null_on_error setting is enabled
     * otherwise returns a value based on the requested return type
     * 
     * @return mixed
     */
    private function getReturnInvalid()
    {
        $type = $this->returnType;

        if ($type === 'query' || $type === 'insertMultiple') {
            //  note that "query" and "insertMultiple" have boolean return values (success or fail). 
            //      no need for them to be null even if return_null_on_error is set
            return false;
        }
        if ($this->settings['return_null_on_error']) {
            return null;
        }
        if ($type === 'one') {
            return '';
        }
        if ($type === 'insert') {
            return 0;
        }

        return array();
    }

    /**
     * after an error, set error information
     * calls exitProgramError
     * 
     * @param PDOStatement $statement
     */
    private function queryErrorSave($statement)
    {
        $errorMsg = 'Query Failed';
        if ($statement) {
            $e  = $statement->errorInfo();
            if (!empty($e)) {
                $errorMsg = implode(' | ', $e);
            }
        } else {
            $e = $this->connection->errorInfo();
            if (!empty($e)) {
                $errorMsg = implode(' | ', $e);
            }
        }
        $this->exitProgramError($errorMsg);
    }

    /**
     * after a successful query, save query information
     * set isSuccess. set rowCount if applicable. set insertId if applicable
     * 
     * @param PDOStatement $statement
     */
    private function querySuccessSave($statement)
    {
        $this->isSuccess = true;
        if ($statement) {
            $rowCount = $statement->rowCount();
            if (!empty($rowCount)) {
                $this->rowCount = $rowCount;
            }
        }

        $sqlFirst6Lc = strtolower(substr(trim($this->sql), 0, 6));
        $type = $this->returnType;
        if ($type === 'insert' || $type === 'insertMultiple' || $sqlFirst6Lc == 'insert') {
            $this->insertId = $this->connection->lastInsertId();
        }
    }

    /**
     * check if a value is a raw SQL value created by the raw() 
     * checks the array('raw_sql'=> $value) format generated by the raw() function
     * returns the raw SQL string or false if the value is not a valid raw SQL value
     *
     * @param mixed $value
     * @return string|false
     */
    private function getRawString($value)
    {
        if (!is_array($value)) {
            return false;
        }
        if (count($value) != 1) {
            return false;
        }
        if (!isset($value['raw_sql'])) {
            return false;
        }
        return $value['raw_sql'];
    }

    /**
     * check a database identifier such as a table or field name
     * should only contain letters, numbers, and underscores.
     * for binds, remove colon, check identifier, and put colon back. this will make sure that the colon will 
     *      not be seen as an invalid character and the colon will be added if it wasn't set in the first place 
     *      ":name" and "name" will both return ":name"
     * if invalid, produce an error (will end the program depending on settings)
     * if invalid and the program settings do not end the program on error, return an empty string.
     * 
     * @param string $identifier
     * @param string $type
     * @param boolean $isBind
     * @return string
     */
    private function checkIdentifier($identifier, $type, $isBind = false)
    {
        if (!is_string($identifier)) {
            $message = $type . ' is not a string (' . gettype($identifier) . ' passed)';
            $this->exitProgramError($message);
            return '';
        }

        if ($isBind) {
            $identifier = ltrim($identifier, ':');
        }

        if (empty($identifier)) {
            $message = $type . ' is empty';
            $this->exitProgramError($message);
            return '';
        }

        if (!preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $identifier)) {
            $message = $type . ' is invalid: ' . $identifier
                . ' | must contain only letters, numbers, and underscores and cannot start with a number';
            $this->exitProgramError($message);
            return '';
        }

        if ($isBind) {
            $identifier = ':' . $identifier;
        }

        return $identifier;
    }

    /**
     * reset information for the current database operation
     */
    private function resetInfo()
    {
        $this->insertId = 0;
        $this->sql = '';
        $this->isSuccess = false;
        $this->rowCount = 0;
        $this->returnType = '';
        $this->binds = array();
        $this->keyField = '';
        $this->valueField = '';
        $this->queryError = '';
        $this->endTime = 0;
        if ($this->settings['save_query_run_time']) {
            $this->startTime = microtime(true);
        } else {
            $this->startTime = 0;
        }
    }

    /**
     * handle a database connection or query error.
     * $isConnectionError is true for connection, initialization, or configuration errors
     * end program (with optional output), continue without database, or continue with database based on settings
     * see connection_error_action, query_error_action, error_output_html, and output_error_debugging settings
     * 
     * @param string $errorMessage
     * @param boolean $isConnectionError
     */
    private function exitProgramError($errorMessage = '', $isConnectionError = false)
    {
        $endProgram = false;
        if ($isConnectionError) {
            $this->lastConnectionError = $errorMessage;
            $this->skipQueries = true;
            if ($this->settings['connection_error_action'] === 'continue_without_database') {
                // continue
            } else {
                $endProgram = true;
            }
        } else {
            $this->queryError = $this->lastQueryError = $errorMessage;
            if ($this->settings['query_error_action'] === 'continue_with_database') {
                // continue
            } elseif ($this->settings['query_error_action'] === 'continue_without_database') {
                $this->skipQueries = true;
            } else {
                $endProgram = true;
            }
        }

        if (!$endProgram) {
            return;
        }

        // output and end the program

        $errorHtml = 'Database Error';
        if (!empty($this->settings['error_output_html'])) {
            $errorHtml = $this->settings['error_output_html'];
        }
        echo "\n\n<br>\n<br>\n<div>\n" . $errorHtml . "</div>";

        if ($this->settings['output_error_debugging']) {
            echo "\n\n<br>\n<br>\n<div>\n" . htmlentities($errorMessage) . "</div><br>\n\n";

            if (!$isConnectionError) {
                $this->displayLastQueryInfo();
            }

            echo "<br>\n\n";

            $backtrace = debug_backtrace();
            $backtraceData = array();
            $databaseHelperFile = realpath(__FILE__);
            foreach ($backtrace as $bt) {
                $file = $line = $function = $class = $args = '';

                if (!empty($bt['file'])) {
                    $file = $bt['file'];
                }

                if (realpath($file) ==  $databaseHelperFile) {
                    // filter out anything in the class itself (this file) 
                    //continue;
                }

                if (!empty($bt['line'])) {
                    $line = $bt['line'];
                }
                if (!empty($bt['class'])) {
                    $class = $bt['class'];
                }
                if (!empty($bt['function'])) {
                    $function = $bt['function'];
                }


                $backtraceData[] = array(
                    'file' => $file,
                    'line' =>  $line,
                    'function' => $function,
                    'class' => $class
                );
            }
            $this->display($backtraceData);
        }

        die();
    }


    // -----------------------------------------------------------------------------
    // Internal Processing Functions (Debugging Display)
    // -----------------------------------------------------------------------------

    /**
     * display a value for debugging
     * called by display() to process and display the value
     * displays arrays with matching row fields as an HTML table
     * recursively displays other arrays as HTML tables
     * uses var_dump for values that cannot be displayed as a table
     * set up as a separate function from display() to avoid have 
     *      the internal $isTopLevel parameter passed to the public display() function
     * 
     * @param mixed $value
     * @param boolean $isTopLevel
     */
    private function displayInternal($value, $isTopLevel = true)
    {
        if ($isTopLevel) {
            echo "\n<style>" .
                ".db_class_preview1 { background-color: #DEF; margin:14px 0; } " .
                "pre.db_class_preview1 { padding: 8px 4px; border:1px solid #777;padding: 0; } " .
                ".db_class_preview1 pre.db_class_preview1 { border: none; padding:0; margin:0 } " .
                "table.db_class_preview1 { border-collapse: collapse; } " .
                "table.db_class_preview1 td, table.db_class_preview1 th { padding: 6px 10px; border: 1px solid #777; } " .
                "table.db_class_preview1 td td { padding: 4px; border: 1px solid #AAA; } " .
                ".db_class_preview1 table.db_class_preview1 { margin:0 } " .
                "</style>\n";
        }

        if (!is_array($value)) {

            if (
                $isTopLevel ||
                (empty($value) && $value !== 0 && $value !== 0.0 && $value !== '0') ||
                (!is_string($value) && !is_int($value) && !is_float($value))
            ) {
                echo "\n<pre class=\"db_class_preview1\">";
                var_dump($value);
                echo "</pre>\n";
            } else {
                echo htmlspecialchars($value);
            }

            return;
        }

        $count = count($value);
        if ($count < 1 || $count > intval($this->settings['max_rows_for_table_display'])) {
            echo "\n<pre class=\"db_class_preview1\">";
            var_dump($value);
            echo "</pre>\n";
            return;
        }

        $is2DArray = true;
        $matchCols = $colKeys = array();
        $colCount  = 0;
        foreach ($value as $row) {

            if (!is_array($row) || count($row) < 1) {
                $is2DArray = false;
                break;
            }

            if ($colCount === 0) {
                // $matchCols will be compared with columns in every other row, in these checks keys must be the same
                $matchCols = $row;
                $colCount = count($row);
                $colKeys = array_keys($row);
            } else {
                if ($colCount !== count($row) || array_diff_key($row, $matchCols)) {
                    $is2DArray = false;
                    break;
                }
            }

            foreach ($row as $col) {
                if (!is_string($col) && !is_int($col) && !is_float($col) && !is_null($col)) {
                    $is2DArray = false;
                    break 2;
                }
            }
        }


        if ($is2DArray) {
            echo "\n<table class=\"db_class_preview1\"><thead><tr><th><i>key</i></th>";
            foreach ($colKeys as $colKey) {
                echo "<th>" . htmlspecialchars($colKey) . "</th>";
            }
            echo "</tr></thead>\n";
            echo "<tbody>\n";
            foreach ($value as $k => $v) {
                echo "<tr><td>" . htmlspecialchars($k) . "</td>";
                foreach ($v as $v2) {
                    if (is_null($v2)) {
                        echo "<td><i>NULL</i></td>";
                    } else {
                        echo "<td>" . htmlspecialchars($v2) . "</td>";
                    }
                }
                echo "</tr>\n";
            }

            echo "</tbody></table>\n";
            return;
        }

        // an array, but not 2d (not easily converted to a row/column table)

        echo "\n<table class=\"db_class_preview1\"><tbody>\n";
        foreach ($value as $k => $v) {
            echo "<tr><td>" . htmlspecialchars($k) . "</td><td>";
            $this->displayInternal($v, false);
            echo "</td></tr>\n";
        }
        echo "</tbody></table>\n";
    }
}
