<?php
/**
 * Class Db - A lightweight PHP database library that simplifies database operations
 */

class Db
{
    // Configuration

    private static $settings = array(
        // how to handle a connection or initialization error
        // valid values: 'exit', 'continue_without_database' 
        'connection_error_action' => 'exit',

        // how to handle a query error - failure while executing a database query
        // valid values: 'exit', 'continue_without_database', 'continue_with_database'
        'query_error_action' => 'continue_without_database',

        // HTML that will be displayed when an error causes the program to exit
        'error_output_html' => '<div>There was an error loading the page</div>',

        // output debugging details to the screen when an error causes the program to exit
        'output_error_debugging' => false,

        // on query error, return null
        'return_null_on_error' => false,

        // the unique identifier column in tables
        'id_field_name' => 'id',

        // maximum number of records to include in each SQL query generated by insertMultiple()
        'max_records_per_insert_query' => 100,

        // DELETE and UPDATE queries require a WHERE clause
        'delete_and_update_require_where' => true,

        // the maximum number of rows to display as an HTML table when outputting an array using the display() function
        'max_rows_for_table_display' => 1000,

        // track processing start and end times (to calculate duration later)
        'save_query_run_time' => false
    );


    // database connection
    private static $connection = null;

    private static $hasDbConnection = false;

    // should we skip all database operations?
    // will be set on error based on the error type and settings
    private static $skipQueries = false;

    // errors - note that errors can come from the database itself for bad queries or from the class receiving invalid parameters
    // last (most recent) error connecting to the database. if set, database queries will be skipped because the database connection failed  
    private static $lastConnectionError = '';
    
    // last (most recent) error from a query. could be due to an invalid parameter passed or an error from the database 
    private static $lastQueryError = '';

    // information on the current/previous database operation
    // will be reset when a new query starts processing
    private static $insertId = 0;
    // note that Mysql's rowCount() should be consistent for UPDATE, DELETE, and INSERT queries,
    //      but for other queries the returned value may depend on the PHP version, database driver, and settings
    private static $rowCount = 0;
    private static $queryError = '';
    private static $isSuccess = false;
    private static $sql = '';
    private static $binds = array();
    private static $returnType = '';
    private static $keyField = '';
    private static $valueField = '';
    private static $startTime = 0;
    private static $endTime = 0;

    public static function connect($dbName, $host, $user, $pass)
    {
        $dbName = self::checkIdentifier($dbName, '__construct() dbname');
        if (empty($dbName)) {
            self::exitProgramError('invalid dbname in class constructor', true);
            self::$connection = null;
            self::$hasDbConnection = false;
            return false;
        }

        $opt = array(
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_SILENT,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        );

        try {
            self::$connection = new PDO(
                'mysql:host=' . $host . ';dbname=' . $dbName . ';charset=utf8mb4',
                $user,
                $pass,
                $opt
            );
        } catch (PDOException $e) {
            self::$connection = null;
            self::$hasDbConnection = false;
            self::exitProgramError($e->getMessage(), true);
            return false;
        }

        self::$hasDbConnection = true;
        self::$skipQueries = false;
        return true;
    }


    // Settings

    // set a configuration setting
    public static function updateSetting($setting, $value)
    {
        if (!isset(self::$settings[$setting])) {
            self::exitProgramError("DatabaseHelper updateSetting() received invalid setting: " . $setting, true);
            return;
        }

        if (
            $setting === 'save_query_run_time' ||
            $setting === 'output_error_debugging' ||
            $setting === 'return_null_on_error' ||
            $setting === 'delete_and_update_require_where'
        ) {
            if (empty($value) || $value === 'false') {
                $value = false;
            } else {
                $value = true;
            }
        } elseif ($setting === 'max_records_per_insert_query' || $setting === 'max_rows_for_table_display') {
            if (!is_numeric($value)) {
                self::exitProgramError("DatabaseHelper updateSetting() value must be a number: " . $setting, true);
                return;
            }
            $value = intval($value);

            // upper limit set to 10k
            if ($setting === 'max_records_per_insert_query' && ($value < 1 || $value > 10000)) {
                self::exitProgramError('value is invalid for setting: max_records_per_insert_query. value must be between 1 and 10,000', true);
                return;
            }

            if ($setting === 'max_rows_for_table_display' && ($value < 2 || $value > 10000)) {
                self::exitProgramError('value is invalid for setting: max_rows_for_table_display. value must be between 2 and 10,000', true);
                return;
            }
        } elseif ($setting === 'connection_error_action') {
            // only valid values
            if ($value !== 'exit' && $value !== 'continue_without_database') {
                self::exitProgramError('value is invalid for setting: connection_error_action. value must be "exit" or "continue_without_database"', true);
                return;
            }
        } elseif ($setting === 'query_error_action') {
            // only valid values
            if ($value !== 'exit' && $value !== 'continue_without_database' && $value !== 'continue_with_database') {
                self::exitProgramError('value is invalid for setting: query_error_action. value must be "exit", "continue_without_database", or "continue_with_database"', true);
                return;
            }
        } elseif ($setting === 'error_output_html') {
            if (!is_string($value)) {
                self::exitProgramError('value is invalid for setting: error_output_html. value must be "string" (' . gettype($value) . ' passed)', true);
                return;
            }
        } elseif ($setting === 'id_field_name') {
            if (!is_string($value)) {
                self::exitProgramError('value is invalid for setting: id_field_name. value must be "string" (' . gettype($value) . ' passed)', true);
                return;
            }
            $value = self::checkIdentifier($value, 'id_field_name setting');
            if (empty($value)) {
                self::exitProgramError('invalid id_field_name setting', true);
                return;
            }
        } else {
            // should not get here. this is just a failsafe in case a valid settings is not checked
            self::exitProgramError("DatabaseHelper updateSetting() setting not available: " . $setting, true);
            return;
        }

        self::$settings[$setting] = $value;
    }


    // Get Last Error and Connection Info

    // return the last (most recent) error
    public static function lastError()
    {
        // note that there will not be both error types since connection errors will stop queries from running
        if (!empty(self::$lastConnectionError)) {
            return self::$lastConnectionError;
        }
        if (!empty(self::$lastQueryError)) {
            return self::$lastQueryError;
        }
        return '';
    }

    // return if a database connection has been made or not
    public static function hasDbConnection()
    {
        return self::$hasDbConnection;
    }


    // Get Last Query Info

    // get the identifier of the last query
    public static function insertId()
    {
        return self::$insertId;
    }

    // get the number of rows affected by the last query
    public static function rowCount()
    {
        return self::$rowCount;
    }

    // get the error from the last query
    public static function error()
    {
        return self::$queryError;
    }

    // return if the last query was successful
    public static function success()
    {
        if (self::$isSuccess) {
            return true;
        }
        return false;
    }

    // return the duration of the last query in seconds
    public static function duration()
    {
        if (self::$startTime && self::$endTime) {
            $duration = self::$endTime - self::$startTime;
            return $duration;
        }
        return 0;
    }

    // return the last SQL query
    public static function sql()
    {
        return self::$sql;
    }

    // return the PDO binds for the last query
    public static function binds()
    {
        return self::$binds;
    }    


    // -----------------------------------------------------------------------------
    // Development / Debugging
    // -----------------------------------------------------------------------------

    // display information about the last query
    public static function displayLastQueryInfo()
    {
        $ar = array(
            'type' => self::$returnType,
            'sql' => self::$sql,
            'binds' => self::$binds,
            'keyField' => self::$keyField,
            'valueField' => self::$valueField,
            'rowCount' => self::$rowCount,
            'insertId' => self::$insertId,
            'isSuccess' => self::$isSuccess,
            'queryError' => self::$queryError
        );
        if (self::$settings['save_query_run_time']) {
            $duration = 0;
            if (self::$startTime && self::$endTime) {
                $duration = self::$endTime - self::$startTime;
            }
            $ar['duration'] = number_format($duration, 6) . ' seconds';
        }

        self::display($ar);
    }

    // shortcut for displayLastQuery
    public static function info()
    {
        self::displayLastQueryInfo();
    }

    // display a value for debugging
    public static function display($value)
    {
        self::displayInternal($value);
    }

    // output a list of all tables in the database

    public static function tables()
    {
        self::resetInfo();
        self::$returnType = 'col';

        self::$sql = 'SHOW TABLES;';

        $tables = self::makeQuery();
        self::display($tables);
    }

    // output a list of all fields in a database table
    public static function fields($table)
    {
        self::resetInfo();
        self::$returnType = 'all';

        $table = self::checkIdentifier($table, 'fields table');
        if (empty($table)) {
            return self::getReturnInvalid();
        }

        self::$sql = 'DESCRIBE `' . $table . '`;';
        $fields = self::makeQuery();

        self::display($fields);
    }


    // -----------------------------------------------------------------------------
    // Retrieve Data From Raw SQL
    // -----------------------------------------------------------------------------

    // execute SQL and return all result rows
    public static function all($sql, $binds = array(), $keyField = '')
    {
        self::resetInfo();
        self::$returnType = 'all';
        self::$sql = $sql;

        self::$binds = $binds;
        self::$keyField = $keyField;

        return self::makeQuery();
    }

    // execute SQL and return the first row
    public static function row($sql, $binds = array())
    {
        self::resetInfo();
        self::$returnType = 'row';
        self::$sql = $sql;

        self::$binds = $binds;

        return self::makeQuery();
    }

    // execute SQL and return all values from a single column
    public static function column($sql, $binds = array(), $keyField = '', $valueField = '')
    {
        self::resetInfo();
        self::$returnType = 'col';
        self::$sql = $sql;
        self::$binds = $binds;
        self::$keyField = $keyField;
        self::$valueField = $valueField;

        return self::makeQuery();
    }

    // shortcut for the column function
    public static function col($sql, $binds = array(), $keyField = '', $valueField = '')
    {
        return self::column($sql, $binds, $keyField, $valueField);
    }

    // execute SQL and return a single value from the first result row
    public static function one($sql, $binds = array(), $valueField = '')
    {
        self::resetInfo();
        self::$returnType = 'one';
        self::$sql = $sql;
        self::$binds = $binds;
        self::$valueField = $valueField;

        return self::makeQuery();
    }


    // Modify Database (Insert, Update, Delete, Alter, etc) From Raw SQL

    // execute SQL when no result values are needed
    public static function query($sql, $binds = array())
    {
        self::resetInfo();
        self::$returnType = 'query';
        self::$sql = $sql;
        self::$binds = $binds;

        return self::makeQuery();
    }


    // Retrieve Data From Parameters (converted to SQL)

    // return the number of rows in a table
    public static function count($table)
    {
        self::resetInfo();
        self::$returnType = 'one';

        $returnInvalid = self::getReturnInvalid();

        $table = self::checkIdentifier($table, 'count() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        self::$sql = 'SELECT COUNT(*) AS `tot` FROM `' . $table . '`;';

        return self::makeQuery();
    }

    // get a row from a table using its identifier field (usually "id")
    public static function rowById($table, $id)
    {
        self::resetInfo();
        self::$returnType = 'row';

        $table = self::checkIdentifier($table, 'rowById() table');
        $idFieldName = self::checkIdentifier(self::$settings['id_field_name'], 'rowById() id_field_name setting');
        if (empty($table) || empty($idFieldName)) {
            return self::getReturnInvalid();
        }

        self::$sql = 'SELECT * FROM `' . $table . '` WHERE `' . $idFieldName . '` = :id limit 1;';
        self::$binds = array(':id' => $id);

        return self::makeQuery();
    }

    // get a single value from a table using its identifier field (usually "id")
    public static function oneById($table, $id, $field)
    {
        self::resetInfo();
        self::$returnType = 'one';

        $table = self::checkIdentifier($table, 'oneById() table');
        $idFieldName = self::checkIdentifier(self::$settings['id_field_name'], 'oneById() id_field_name setting');
        $field = self::checkIdentifier($field, 'oneById() field');
        if (empty($table) || empty($idFieldName) || empty($field)) {
            return self::getReturnInvalid();
        }

        self::$sql = 'SELECT `' . $field . '` FROM `' . $table . '` WHERE `' . $idFieldName . '` = :id LIMIT 1;';
        self::$binds = array(':id' => $id);

        return self::makeQuery();
    }


    // Modify Database (Insert, Update, Delete, Alter, etc) From Parameters (converted to SQL)

    // insert a new row into a table
    public static function insert($table, $values)
    {
        self::resetInfo();
        self::$returnType = 'insert';

        $returnInvalid = self::getReturnInvalid();
        $table = self::checkIdentifier($table, 'insert() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($values)) {
            self::exitProgramError('insert() - $values is not an array (' . gettype($values) . ' passed)');
            return $returnInvalid;
        }
        if (count($values) < 1) {
            self::exitProgramError('insert() - $values array is empty (0 values)');
            return $returnInvalid;
        }

        $fieldStr = $valueStr = '';
        $binds = array();
        $sep = '';
        foreach ($values as $field => $value) {
            $field = self::checkIdentifier($field, 'insert() field (array key)');
            if (empty($field)) {
                return $returnInvalid;
            }
            $fieldStr .= $sep . '`' . $field . '`';
            $rawSql = self::getRawString($value);
            if ($rawSql) {
                $valueStr .= $sep . ' ' . $rawSql . ' ';
            } else {
                $valueStr .= $sep . ':' . $field;
                $binds[':' . $field] = $value;
            }
            $sep = ', ';
        }
        self::$sql = 'INSERT INTO `' . $table . '` (' . $fieldStr . ') VALUES (' . $valueStr . ');';
        self::$binds = $binds;

        return self::makeQuery();
    }

    // insert a new row into a table
    public static function insertMultiple($table, $rows)
    {
        self::resetInfo();
        self::$returnType = 'insertMultiple';

        $returnInvalid = self::getReturnInvalid();

        $table = self::checkIdentifier($table, 'insertMultiple() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($rows)) {
            self::exitProgramError('insertMultiple() - $rows is not an array (' . gettype($rows) . ' passed)');
            return $returnInvalid;
        }
        if (count($rows) < 1) {
            self::exitProgramError('InsertMultiple() - $rows array is empty (0 rows)');
            return $returnInvalid;
        }

        // default value, will change after inserts
        $returnValue = $returnInvalid;

        // pre-check all rows
        $matchRow = array();
        $rowKeys = array();
        $matchRowCount = 0;
        foreach ($rows as $row) {
            if (!is_array($row)) {
                self::exitProgramError('InsertMultiple() - $rows is not a 2 dimensional array');
                return $returnInvalid;
            }

            if (empty($matchRow)) {
                // our first row that we will use to compare to others has not been set yet
                // do some validation and set it

                if (count($row) < 1) {
                    self::exitProgramError('InsertMultiple() - the first row in $rows is empty (0 fields)');
                    return $returnInvalid;
                }
                foreach ($row as $field => $value) {
                    $fieldClean = self::checkIdentifier($field, 'insertMultiple() row field (array key)', true);
                    if (empty($fieldClean)) {
                        self::exitProgramError('InsertMultiple() - $row has a row with an invalid field name (array key)');
                        return $returnInvalid;
                    }
                }

                // $matchRow will be compared with every other row, in these checks keys must be the same
                $matchRow = $row;
                $matchRowCount = count($matchRow);
                $rowKeys = array_keys($matchRow);
            } else {
                if ($matchRowCount !== count($row)  || array_diff_key($row, $matchRow)) {
                    self::exitProgramError('InsertMultiple() - mismatched field name (array key) in $rows');
                    return $returnInvalid;
                }
            }
        }

        $fieldStr = '';
        foreach ($rowKeys as $key) {
            if (!empty($fieldStr)) {
                $fieldStr .= ',';
            }
            $fieldStr .= '`' . $key . '`';
        }

        $maxInsertRows = intval(self::$settings['max_records_per_insert_query']);

        $valStr = '';
        $binds = array();
        $ctr = 0;
        $isFirstRow = true;
        foreach ($rows as $row) {
            $ctr++;
            if ($isFirstRow) {
                $isFirstRow = false;
            } else {
                $valStr .= ',';
            }

            $isFirstField = true;
            $valStr .= '(';
            $fieldCtr = 0;
            foreach ($rowKeys as $field) {
                $fieldCtr++;
                if ($isFirstField) {
                    $isFirstField = false;
                } else {
                    $valStr .= ',';
                }
                $rawSql = self::getRawString($row[$field]);
                if ($rawSql) {
                    $valStr .= ' ' . $rawSql . ' ';
                } else {
                    $bindKey = ':v' . $ctr . '_' . $fieldCtr;
                    $valStr .= $bindKey;
                    $binds[$bindKey] = $row[$field];
                }
            }
            $valStr .= ')';

            if ($ctr >= $maxInsertRows) {
                self::$sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
                self::$binds = $binds;
                $returnValue = self::makeQuery();
                if (!$returnValue) {
                    return $returnInvalid;
                }
                // reset to start building next insert
                $isFirstRow = true;
                $valStr = '';
                $binds = array();
                $ctr = 0;
            }
        }

        if (!empty($valStr)) {
            // insert remaining unprocessed records
            self::$sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
            self::$binds = $binds;
            $returnValue = self::makeQuery();
            if (!$returnValue) {
                return $returnInvalid;
            }
        }

        return $returnValue;
    }

    // insert multiple new rows into a table using a separate array of field names
    public static function insertMultipleFieldsValues($table, $fields, $dataRows)
    {
        self::resetInfo();
        self::$returnType = 'insertMultiple';

        $returnInvalid = self::getReturnInvalid();

        $table = self::checkIdentifier($table, 'insertMultipleFieldsValues() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($fields)) {
            self::exitProgramError('insertMultipleFieldsValues() - $fields is not an array (' . gettype($fields) . ' passed)');
            return $returnInvalid;
        }

        $fieldCount = count($fields);
        if ($fieldCount < 1) {
            self::exitProgramError('insertMultipleFieldsValues() - $fields array is empty (0 fields)');
            return $returnInvalid;
        }
        if (count(array_unique($fields)) !== $fieldCount) {
            self::exitProgramError('insertMultipleFieldsValues() - $fields values must be unique');
            return $returnInvalid;
        }

        if (!is_array($dataRows)) {
            self::exitProgramError('insertMultipleFieldsValues() - $dataRows is not an array (' . gettype($dataRows) . ' passed)');
            return $returnInvalid;
        }
        if (count($dataRows) < 1) {
            self::exitProgramError('insertMultipleFieldsValues() - $dataRows array is empty (0 rows)');
            return $returnInvalid;
        }

        // default value, will change after inserts
        $returnValue = $returnInvalid;

        // pre-check all rows

        foreach ($dataRows as $row) {
            if (!is_array($row)) {
                self::exitProgramError('insertMultipleFieldsValues() - $dataRows is not a 2 dimensional array');
                return $returnInvalid;
            }

            if ($fieldCount !== count($row)) {
                self::exitProgramError('insertMultipleFieldsValues() - mismatched field count in $dataRows rows');
                return $returnInvalid;
            }
        }

        $fieldStr = '';
        foreach ($fields as $field) {
            $field = self::checkIdentifier($field, 'insertMultipleFieldsValues() field');
            if (empty($field)) {
                return $returnInvalid;
            }

            if (!empty($fieldStr)) {
                $fieldStr .= ',';
            }
            $fieldStr .= '`' . $field . '`';
        }

        $maxInsertRows = intval(self::$settings['max_records_per_insert_query']);

        $valStr = '';
        $binds = array();
        $ctr = 0;
        $isFirstRow = true;
        foreach ($dataRows as $row) {
            $ctr++;
            if ($isFirstRow) {
                $isFirstRow = false;
            } else {
                $valStr .= ',';
            }

            $isFirstField = true;
            $valStr .= '(';
            $valCtr = 0;
            foreach ($row as $value) {
                if ($isFirstField) {
                    $isFirstField = false;
                } else {
                    $valStr .= ',';
                }
                $valCtr++;

                $rawSql = self::getRawString($value);
                if ($rawSql) {
                    $valStr .= ' ' . $rawSql . ' ';
                } else {
                    $bindKey = ':v' . $ctr . '_' . $valCtr;
                    $valStr .= $bindKey;
                    $binds[$bindKey] = $value;
                }
            }
            $valStr .= ')';

            if ($ctr >= $maxInsertRows) {
                self::$sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
                self::$binds = $binds;
                $returnValue = self::makeQuery();
                if (!$returnValue) {
                    return $returnInvalid;
                }

                // reset to start building next insert
                $isFirstRow = true;
                $valStr = '';
                $binds = array();
                $ctr = 0;
            }
        }

        if (!empty($valStr)) {
            self::$sql = 'insert into `' . $table . '` (' . $fieldStr . ') values ' . $valStr . ';';
            self::$binds = $binds;
            $returnValue = self::makeQuery();
            if (!$returnValue) {
                return $returnInvalid;
            }
        }

        return $returnValue;
    }

    // update rows in a table
    public static function update($table, $values, $whereSql, $whereBinds = array())
    {
        self::resetInfo();
        self::$returnType = 'query';

        $returnInvalid = self::getReturnInvalid();

        $table = self::checkIdentifier($table, 'update() table');
        if (empty($table)) {
            return $returnInvalid;
        }

        if (!is_array($values)) {
            self::exitProgramError('update() - $values is not an array (' . gettype($values) . ' passed)');
            return $returnInvalid;
        }
        if (count($values) < 1) {
            self::exitProgramError('update() - $values array is empty (0 values)');
            return $returnInvalid;
        }

        if (!is_string($whereSql)) {
            self::exitProgramError('update() - $whereSql is not a string (' . gettype($whereSql) . ' passed)');
            return $returnInvalid;
        }
        if (empty($whereSql)) {
            self::exitProgramError('update() - $whereSql is empty');
            return $returnInvalid;
        }


        $setStr = '';
        $binds = $whereBinds;
        $ctr = 0;
        foreach ($values as $field => $value) {
            $ctr++;
            $field = self::checkIdentifier($field, 'update() field');
            if (empty($field)) {
                return $returnInvalid;
            }

            if (!empty($setStr)) {
                $setStr .= ',';
            }
            $bindKey = ':v' . $ctr;
            while (isset($binds[$bindKey]) || isset($binds[ltrim($bindKey, ':')])) {
                // there was a collision in the naming, move on to the next counter.
                $ctr++;
                $bindKey = ':v' . $ctr;
            }
            $rawSql = self::getRawString($value);
            if ($rawSql !== false) {
                $setStr .= '`' . $field . '`=' . $rawSql . ' ';
            } else {
                $setStr .= '`' . $field . '`=' . $bindKey;
                $binds[$bindKey] = $value;
            }
        }

        self::$sql = 'UPDATE `' . $table . '` SET ' . $setStr . ' WHERE ' . $whereSql . ';';
        self::$binds = $binds;
        return self::makeQuery();
    }

    // update a row in a table using its identifier field (usually "id")
    public static function updateById($table, $values, $id)
    {
        // reset needed even though the update function will reset again.
        // but if errors are generated in this function, we don't want previous query info in debugging output
        self::resetInfo();
        self::$returnType = 'query';

        $returnInvalid = self::getReturnInvalid();

        $table = self::checkIdentifier($table, 'updateById() table');
        if (empty($table)) {
            return $returnInvalid;
        }
        $idFieldName = self::checkIdentifier(self::$settings['id_field_name'], 'updateById() id_field_name setting');
        if (empty($idFieldName)) {
            return $returnInvalid;
        }

        $whereSql = '`' . $idFieldName . '`=:id';
        $binds = array(':id' => $id);
        return self::update($table, $values, $whereSql, $binds);
    }

    // delete a row from a table using its identifier field (usually "id")
    public static function deleteById($table, $id)
    {
        self::resetInfo();
        self::$returnType = 'query';

        $returnInvalid = self::getReturnInvalid();

        $table = self::checkIdentifier($table, 'deleteById() table');
        $idFieldName = self::checkIdentifier(self::$settings['id_field_name'], 'deleteById() id_field_name setting');
        if (empty($table) || empty($idFieldName)) {
            return $returnInvalid;
        }

        self::$sql = 'DELETE FROM `' . $table . '` WHERE `' . $idFieldName . '`=:id;';
        self::$binds = array(':id' => $id);

        return self::makeQuery();
    }


    // SQL Expression Helpers

    // mark a value as raw SQL instead of a value to be bound
    public static function raw($value)
    {
        return array('raw_sql' => $value);
    }

    
    // Internal Processing Functions (Queries)

    // prepare and execute SQL
    private static function makeQuery()
    {
        $returnInvalid = self::getReturnInvalid();

        if (self::$skipQueries) {
            if (empty(self::$queryError)) {
                self::$queryError = 'Query skipped due to previous error';
            }
            return  $returnInvalid;
        }

        $sql = self::$sql;
        if (!is_string($sql)) {
            self::exitProgramError('makeQuery() - $sql is not a string');
            return $returnInvalid;
        }

        // trim the class and function variables
        self::$sql = $sql = trim($sql);
        if (empty($sql)) {
            self::exitProgramError('makeQuery() - $sql is empty');
            return $returnInvalid;
        }

        $binds = self::$binds;
        // convert any falsy value to an empty array. this allows any falsey (null, false, '') to be passed when there are no binds
        if (empty($binds)) {
            $binds = array();
        }
        if (!is_array($binds)) {
            self::exitProgramError('makeQuery() - $binds must be an array');
            return $returnInvalid;
        }

        // to avoid mistakes, if delete_and_update_require_where is set, UPDATE and DELETE queries require WHERE
        // note that this is a simple test that sql has the string "WHERE". so "delete from places_where_ive_been;" will incorrectly 
        //    be seen as having a WHERE clause
        if (!empty(self::$settings['delete_and_update_require_where'])) {
            // check if it's an UPDATE or DELETE query 
            $sqlFirst6Lc = strtolower(substr($sql, 0, 6));
            if ($sqlFirst6Lc === 'update' || $sqlFirst6Lc === 'delete') {
                // check if the string "WHERE" is in the SQL
                if (stripos($sql, 'where') === false) {
                    self::exitProgramError(strtoupper($sqlFirst6Lc) . ' query requires a WHERE clause');
                    return $returnInvalid;
                }
            }
        }

        $statement = self::$connection->prepare($sql);
        if (!$statement) {
            //self::$setInfo(false, $statement);
            self::queryErrorSave($statement);
            return $returnInvalid;
        }

        foreach ($binds as $field => $value) {
            $field = self::checkIdentifier($field, 'bind field', true);
            if (empty($field)) {
                return $returnInvalid;
            }
            $success =  $statement->bindValue($field, $value);
            if (!$success) {
                self::queryErrorSave($statement);
                return $returnInvalid;
            }
        }
        $success = $statement->execute();

        if (self::$settings['save_query_run_time']) {
            self::$endTime = microtime(true);
        }

        if (!$success) {
            self::queryErrorSave($statement);
            return $returnInvalid;
        }

        self::querySuccessSave($statement);

        return self::getReturnValue($statement);
    }

    // process query results and return the appropriate value
    private static function getReturnValue($statement)
    {
        $returnInvalid = self::getReturnInvalid();

        $type = self::$returnType;

        if (!$statement) {
            return $returnInvalid;
        }

        $keyField = self::$keyField;
        $valueField = self::$valueField;

        if ($type == 'all') {
            $fetchAll = $statement->fetchAll(PDO::FETCH_ASSOC);
            if (empty($keyField)) {
                return $fetchAll;
            }

            $ar = array();
            foreach ($fetchAll as $row) {
                if (!array_key_exists($keyField, $row)) {
                    self::exitProgramError("key field ($keyField) is not found. available fields: " . implode(', ', array_keys($row)));
                    return $returnInvalid;
                }
                $ar[$row[$keyField]] = $row;
            }
            return $ar;
        }

        if ($type == 'row') {
            $row = $statement->fetch(PDO::FETCH_ASSOC);

            if (!$row) {
                return array();
            }
            return $row;
        }

        if ($type == 'col') {
            $ar = array();
            if (empty($keyField) && empty($valueField)) {
                $val = $statement->fetchColumn();
                while ($val !== false) {
                    $ar[] = $val;
                    $val = $statement->fetchColumn();
                }
                return $ar;
            }

            $fetchAll = $statement->fetchAll(PDO::FETCH_ASSOC);
            foreach ($fetchAll as $row) {
                $k = $v = null;

                if (!empty($valueField)) {
                    if (!array_key_exists($valueField, $row)) {
                        self::exitProgramError("value field ($valueField) is not found. available fields: " . implode(', ', array_keys($row)));
                        return $returnInvalid;
                    }
                    $v = $row[$valueField];
                } else {
                    $v = reset($row);
                }

                if (!empty($keyField)) {
                    if (!array_key_exists($keyField, $row)) {
                        self::exitProgramError("key field ($keyField) is not found. available fields: " . implode(', ', array_keys($row)));
                        return $returnInvalid;
                    }
                    $k = $row[$keyField];
                }

                if (!is_null($k)) {
                    $ar[$k] = $v;
                } else {
                    $ar[] = $v;
                }
            }
            return $ar;
        }

        if ($type == 'one') {
            if (empty($valueField)) {
                $row = $statement->fetch(PDO::FETCH_NUM);
                if ($row) {
                    return $row[0];
                }
            } else {
                $row = $statement->fetch(PDO::FETCH_ASSOC);
                if ($row) {
                    if (!array_key_exists($valueField, $row)) {
                        self::exitProgramError("value field ($valueField) is not found. available fields: " . implode(', ', array_keys($row)));
                        return $returnInvalid;
                    }
                    return $row[$valueField];
                }
            }
            return '';
        }

        if ($type == 'insert') {
            return self::$insertId;
        }

        return true;
    }

    // determine the value to return when a query fails or returns no results
    private static function getReturnInvalid()
    {
        $type = self::$returnType;

        if ($type === 'query' || $type === 'insertMultiple') {
            return false;
        }
        if (self::$settings['return_null_on_error']) {
            return null;
        }
        if ($type === 'one') {
            return '';
        }
        if ($type === 'insert') {
            return 0;
        }

        return array();
    }

    // after an error, set error information
    private static function queryErrorSave($statement)
    {
        $errorMsg = 'Query Failed';
        if ($statement) {
            $e  = $statement->errorInfo();
            if (!empty($e)) {
                $errorMsg = implode(' | ', $e);
            }
        } else {
            $e = self::$connection->errorInfo();
            if (!empty($e)) {
                $errorMsg = implode(' | ', $e);
            }
        }
        self::exitProgramError($errorMsg);
    }

    // after a successful query, save query information
    private static function querySuccessSave($statement)
    {
        self::$isSuccess = true;
        if ($statement) {
            $rowCount = $statement->rowCount();
            if (!empty($rowCount)) {
                self::$rowCount = $rowCount;
            }
        }

        $sqlFirst6Lc = strtolower(substr(trim(self::$sql), 0, 6));
        $type = self::$returnType;
        if ($type === 'insert' || $type === 'insertMultiple' || $sqlFirst6Lc == 'insert') {
            self::$insertId = self::$connection->lastInsertId();
        }
    }

    // check if a value is a raw SQL value created by the raw() 
    private static function getRawString($value)
    {
        if (!is_array($value)) {
            return false;
        }
        if (count($value) != 1) {
            return false;
        }
        if (!isset($value['raw_sql'])) {
            return false;
        }
        return $value['raw_sql'];
    }

    // check a database identifier such as a table or field name
    private static function checkIdentifier($identifier, $type, $isBind = false)
    {
        if (!is_string($identifier)) {
            $message = $type . ' is not a string (' . gettype($identifier) . ' passed)';
            self::exitProgramError($message);
            return '';
        }

        if ($isBind) {
            $identifier = ltrim($identifier, ':');
        }

        if (empty($identifier)) {
            $message = $type . ' is empty';
            self::exitProgramError($message);
            return '';
        }

        if (!preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $identifier)) {
            $message = $type . ' is invalid: ' . $identifier
                . ' | must contain only letters, numbers, and underscores and cannot start with a number';
            self::exitProgramError($message);
            return '';
        }

        if ($isBind) {
            $identifier = ':' . $identifier;
        }

        return $identifier;
    }

    // reset information for the current database operation
    private static function resetInfo()
    {
        self::$insertId = 0;
        self::$sql = '';
        self::$isSuccess = false;
        self::$rowCount = 0;
        self::$returnType = '';
        self::$binds = array();
        self::$keyField = '';
        self::$valueField = '';
        self::$queryError = '';
        self::$endTime = 0;
        if (self::$settings['save_query_run_time']) {
            self::$startTime = microtime(true);
        } else {
            self::$startTime = 0;
        }
    }

    // handle a database connection or query error.
    private static function exitProgramError($errorMessage = '', $isConnectionError = false)
    {
        $endProgram = false;
        if ($isConnectionError) {
            self::$lastConnectionError = $errorMessage;
            self::$skipQueries = true;
            if (self::$settings['connection_error_action'] === 'continue_without_database') {
                // continue
            } else {
                $endProgram = true;
            }
        } else {
            self::$queryError = self::$lastQueryError = $errorMessage;
            if (self::$settings['query_error_action'] === 'continue_with_database') {
                // continue
            } elseif (self::$settings['query_error_action'] === 'continue_without_database') {
                self::$skipQueries = true;
            } else {
                $endProgram = true;
            }
        }

        if (!$endProgram) {
            return;
        }

        // output and end the program

        $errorHtml = 'Database Error';
        if (!empty(self::$settings['error_output_html'])) {
            $errorHtml = self::$settings['error_output_html'];
        }
        echo "\n\n<br>\n<br>\n<div>\n" . $errorHtml . "</div>";

        if (self::$settings['output_error_debugging']) {
            echo "\n\n<br>\n<br>\n<div>\n" . htmlentities($errorMessage) . "</div><br>\n\n";

            if (!$isConnectionError) {
                self::displayLastQueryInfo();
            }

            echo "<br>\n\n";

            $backtrace = debug_backtrace();
            $backtraceData = array();
            $databaseHelperFile = realpath(__FILE__);
            foreach ($backtrace as $bt) {
                $file = $line = $function = $class = $args = '';

                if (!empty($bt['file'])) {
                    $file = $bt['file'];
                }

                if (realpath($file) ==  $databaseHelperFile) {
                    // filter out anything in the class itself (this file) 
                    continue;
                }

                if (!empty($bt['line'])) {
                    $line = $bt['line'];
                }
                if (!empty($bt['class'])) {
                    $class = $bt['class'];
                }
                if (!empty($bt['function'])) {
                    $function = $bt['function'];
                }


                $backtraceData[] = array(
                    'file' => $file,
                    'line' =>  $line,
                    'function' => $function,
                    'class' => $class
                );
            }
            self::display($backtraceData);
        }

        die();
    }


    // -----------------------------------------------------------------------------
    // Internal Processing Functions (Debugging Display)
    // -----------------------------------------------------------------------------

    // display a value for debugging
    private static function displayInternal($value, $isTopLevel = true)
    {
        if ($isTopLevel) {
            echo "\n<style>" .
                ".db_class_preview1 { background-color: #DEF; margin:14px 0; } " .
                "pre.db_class_preview1 { padding: 8px 4px; border:1px solid #777;padding: 0; } " .
                ".db_class_preview1 pre.db_class_preview1 { border: none; padding:0; margin:0 } " .
                "table.db_class_preview1 { border-collapse: collapse; } " .
                "table.db_class_preview1 td, table.db_class_preview1 th { padding: 6px 10px; border: 1px solid #777; } " .
                "table.db_class_preview1 td td { padding: 4px; border: 1px solid #AAA; } " .
                ".db_class_preview1 table.db_class_preview1 { margin:0 } " .
                "</style>\n";
        }

        if (!is_array($value)) {

            if (
                $isTopLevel ||
                (empty($value) && $value !== 0 && $value !== 0.0 && $value !== '0') ||
                (!is_string($value) && !is_int($value) && !is_float($value))
            ) {
                echo "\n<pre class=\"db_class_preview1\">";
                var_dump($value);
                echo "</pre>\n";
            } else {
                echo htmlspecialchars($value);
            }

            return;
        }

        $count = count($value);
        if ($count < 1 || $count > intval(self::$settings['max_rows_for_table_display'])) {
            echo "\n<pre class=\"db_class_preview1\">";
            var_dump($value);
            echo "</pre>\n";
            return;
        }

        $is2DArray = true;
        $matchCols = $colKeys = array();
        $colCount  = 0;
        foreach ($value as $row) {

            if (!is_array($row) || count($row) < 1) {
                $is2DArray = false;
                break;
            }

            if ($colCount === 0) {
                // $matchCols will be compared with columns in every other row, in these checks keys must be the same
                $matchCols = $row;
                $colCount = count($row);
                $colKeys = array_keys($row);
            } else {
                if ($colCount !== count($row) || array_diff_key($row, $matchCols)) {
                    $is2DArray = false;
                    break;
                }
            }

            foreach ($row as $col) {
                if (!is_string($col) && !is_int($col) && !is_float($col) && !is_null($col)) {
                    $is2DArray = false;
                    break 2;
                }
            }
        }


        if ($is2DArray) {
            echo "\n<table class=\"db_class_preview1\"><thead><tr><th><i>key</i></th>";
            foreach ($colKeys as $colKey) {
                echo "<th>" . htmlspecialchars($colKey) . "</th>";
            }
            echo "</tr></thead>\n";
            echo "<tbody>\n";
            foreach ($value as $k => $v) {
                echo "<tr><td>" . htmlspecialchars($k) . "</td>";
                foreach ($v as $v2) {
                    if (is_null($v2)) {
                        echo "<td><i>NULL</i></td>";
                    } else {
                        echo "<td>" . htmlspecialchars($v2) . "</td>";
                    }
                }
                echo "</tr>\n";
            }

            echo "</tbody></table>\n";
            return;
        }

        echo "\n<table class=\"db_class_preview1\"><tbody>\n";
        foreach ($value as $k => $v) {
            echo "<tr><td>" . htmlspecialchars($k) . "</td><td>";
            self::displayInternal($v, false);
            echo "</td></tr>\n";
        }
        echo "</tbody></table>\n";
    }
}